### ISSUE TITLE
[FEATURE]: Open Container is mapped to DPAD-UP on gamepad

### ISSUE THREAD

**Issue by lambdacdm1** [MissCorruption/QuickLootIE#47] opened 2024-08-05 18:25 UTC
### What happened?

Currently, open container / take one / take all are hardcoded to the favorites key / activate / ready weapon, respectively. However on gamepad, the favorites key is by default tied to DPAD Up, which is needed to navigate the QuickLootIE menu.

One way to alleviate this issue would be to add an option to change keybindings, or to move away from using favorites as the key.

### Version

2.0.0

### What Skyrim version are you using?

1.6.1170

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MissCorruption** [comment] 2024-09-07 17:40
Duplicate of #51, closing this. I don't want multiple issues tracking similar things.

**Closed by MissCorruption** 2024-09-07 17:40 UTC
Labels: bug, enhancement
