### ISSUE TITLE
[Bug]: issue from modpage (psychesvirtue) just saw the link here, apologies if this isnt necessary.

### ISSUE THREAD

**Issue by necriot** [MissCorruption/QuickLootIE#55] opened 2024-09-08 21:20 UTC
### What happened?

i expect it to let me select items normally without stopping out of nowhere (not sarcasm or passive aggressive, just to clarify). i use a ps4 dualshock controller, and at random times it just stops taking dpad input. i can take items but I cant choose between them, and its gotten really really annoying repeatedly. idk if its a problem with the mod, something addressed already, something wrong with my controller or whatever but i'd really like some sort of insight into what in the world is happening.

maybe related to the first bug report here https://www.nexusmods.com/skyrimspecialedition/mods/69980?tab=bugs&BH=4
"stops working after normal looting"

### Version

2.0.0

### What Skyrim version are you using?

1.6.640

### Relevant log output

```shell
no idea what to put here.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AtomCrafty** [comment] 2024-10-31 22:22
I'm not sure what could be causing this, but there is a good chance it will be fixed when we reimplement the input system for #51.

**Comment by AtomCrafty** [comment] 2024-11-17 15:01
I think we can close this.

**Comment by MissCorruption** [comment] 2024-11-17 16:51
Yea, this can be closed. In all my testing I couldn't reproduce it.

**Closed by MissCorruption** 2024-11-17 16:51 UTC
Labels: bug
